---------------------------------------------------------------
-- DETECT DDL/DCL/CONFIG CHANGES IN SNOWFLAKE ACCOUNT
-- Use these queries to identify when changes happen based on last 24 hours of query history, and
-- then trigger backup scripts accordingly
---------------------------------------------------------------

-- 1. DDL changes (CREATE, ALTER, DROP) in the last 24 hours
SELECT
  QUERY_TYPE,
  DATABASE_NAME,
  SCHEMA_NAME,
  USER_NAME,
  ROLE_NAME,
  START_TIME,
  QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE (QUERY_TYPE LIKE 'CREATE%' OR QUERY_TYPE LIKE 'ALTER%' OR QUERY_TYPE LIKE 'DROP%')
  AND START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND (DATABASE_NAME IS NULL OR (DATABASE_NAME NOT LIKE 'USER$%' AND DATABASE_NAME NOT IN ('SNOWFLAKE''TEMPDB'))
  ORDER BY START_TIME DESC;

-- 2. DCL changes (GRANT, REVOKE) in the last 24 hours
SELECT
  QUERY_TYPE,
  USER_NAME,
  ROLE_NAME,
  START_TIME,
  QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE (QUERY_TYPE LIKE 'GRANT%' OR QUERY_TYPE LIKE 'REVOKE%')
  AND START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND QUERY_TEXT NOT ILIKE '%USER$%'
ORDER BY START_TIME DESC;

-- 3. ALL DDL/DCL/Config changes combined (trigger check)
SELECT COUNT(*) AS change_count
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TYPE LIKE ANY ('CREATE%', 'ALTER%', 'DROP%', 'GRANT%', 'REVOKE%')
  AND START_TIME >= DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND (DATABASE_NAME IS NULL OR (DATABASE_NAME NOT LIKE 'USER$%' AND DATABASE_NAME <> 'SNOWFLAKE'))
  AND QUERY_TEXT NOT ILIKE '%TEMPORARY%';
